[package]
name = "pushups"
version = "0.1.0"
authors = ["belfz <marcinbar1@gmail.com>"]

[dependencies]
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"
chrono = "0.4"
clippy = {version = "*", optional = true}

[features]
default = []
